# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21a705367c79f87a118576a0579276eb0d9e25edc5a5077b28ee4ab2b93e174da3834494cfa33ee7ab757e29f747215fb5a742f4ab1b0f8367fe825d91fd31e

test:
  secret_key_base: ce61718ccb67dd1437d99c07b80181bbd7899c2fb0029adb8564f121d9c1f775b9c7cef2530f274ea2db4ac89b7c2cbd2d9fc17c6de466bba454d3b5c448e2b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
